### ISSUE TITLE
Isn't there any manual for these scripts?

### ISSUE THREAD

**Issue by laichiaheng** [wiiaboo/mpv-scripts#3]
How do we use these scripts?

**Comment by wiiaboo** [comment]
Mine all have a few lines at the start explaining the functionality and how to use them.
The ones from wm4 might not have such instructions.

**Comment by Rabcor** [comment]
The explanation is a little bit short and not very in-depth, you don't explain how to find out which conditions are available though (my undersatnding is that mpv --list-properties shows the list of possible properties which are used for the conditions right?) nor how to figure out more in-depth how to use each property

for example property video-params, knowing that it's a property you can use is basically not gonna help you, unless you also know for instance that video-params/w queries the source file's resolution width and video-params/h resolution height, so

`profile-desc=cond:(p["video-params/w"] >1920 or p["video-params/h"] >1080)`

Allows a profile to activate when the video source width is higher than 1920 or height is higher than 1080 (e.g. activates when you would downscale on a 1080p screen,

Your explanation at the start of the script didn't provide much help for figuring this out and I had to google through other smarter people's applications of your script in order to deduce this possible combination of conditions.... How on earth could I possibly have guessed that I'd need to add /h and /w to the property? There was just no way.

Also cond:p stands for property right? is there anything else than p possible for cond? your explanation doesn't say anything about that either (and if there isn't, why even write 'p'?)

**Comment by deus0ww** [comment]
That script is now built-in to MPV (git HEAD). I would use that instead. Manual: https://mpv.io/manual/master/#conditional-auto-profiles

**Comment by Rabcor** [comment]
@wiiaboo it may be a bit soon to remove the script entirely; although it's been implemented upstream it's not in the stable release of mpv yet, so most people might still need it separately.

**Comment by wiiaboo** [comment]
It's right [here](https://github.com/mpv-player/mpv/blob/master/player/lua/auto_profiles.lua), just use it directly.
Or if that doesn't work, it's still on the history of this repo, [here](https://github.com/wiiaboo/mpv-scripts/blob/17e2a1d7e3595e5d490340d6b23512739358cf8d/auto-profiles.lua)
